### ISSUE TITLE
M1 Mac で途中で接続を外すと認識できない現象が発生

### ISSUE THREAD

**Issue by elie-j** [chirimen-oh/PiZeroWebSerialConsole#22]
- チュートリアルを行って、Lチカまで問題なく行った後に、一回接続を外し、Macに差し直したら、その後Mac側で認識されなくなった。
- 最初上手く言っていた時は、ブートとしてMac側で読み込まれていたのだが、それが出なくなった。
- 自身で調べてみた結果、
どうやらOSを新しく書き直すと繋がった。
ネットワークの設定を書くところまでは、やったあとにリブートしてもちゃんと行くが、新しくいファイルを入れるタイミングなのか、プログラムを書いたタイミングか、NPM周りを何かインストールしたタイミングで、それやったあとに外しちゃうと読み込めなくなるみたい。
毎回OSを入れ直せば認識をしてくれるんですけど・・・

とのこと。

**Comment by sizuhiko** [comment]
MacでUSB一覧を表示するコマンド

> ioreg -p IOUSB

**Comment by satakagi** [comment]
* ChromeのwebSerial以前に、macintosh OS側で、何らかのUSBデバイスが認識されている状況なのか、まったく何も認識されていない状況なのか？
  * ioreg -p IOUSB
* もし何も認識されていない場合、　https://gist.github.com/satakagi/dd34c29b0192540080681e2443258282　に従って、cmdline.txtと、config.txtに記載がされているか確認してみては。
* さらに、上記の設定をし直して再起動したらUSBデバイスとして認識されるか確認してみては。

**Comment by gurezo** [comment]
動作確認１回目：現象再現`しない`

手順

1. chirmen lite SD ([2022-12-12-chirimen-lite](https://github.com/chirimen-oh/chirimen-lite/releases/tag/v1.2.0))装着
2. M1 Mac 接続
3. OS 起動待ち
4. Web Serail 接続
5. wi-fi 設定
6. OS再起動
7. `起動完了を見計らって` 、Web Serail 接続
8. Lチカ回路ブレッド接続
9. Lチカプログラムダウンロード
10. Lチカ実行
11. 動作確認完了
12. USBケーブル取り外し
13. 10カウント
14. 再度USBケーブル接続
15. OS 起動待ち
16. Web Serail 接続
17. 接続完了 `※1`
    ![スクリーンショット_2023-08-25_0_06_10](https://github.com/chirimen-oh/PiZeroWebSerialConsole/assets/7631567/1999538a-7e23-48ad-8471-535110262ab6)
18. cd コマンド入力して、myApp ディレクトリへ移動 `※2`
    ![スクリーンショット_2023-08-25_0_06_32](https://github.com/chirimen-oh/PiZeroWebSerialConsole/assets/7631567/bb0d105e-112d-414c-a67f-133e76564264)
19. 以降、上記10, 11 を実施


```
.<CONNECTED>>
Raspbian GNU/Linux 11 raspberrypi ttyGS0

raspberrypi login: 
raspberrypi login: pi
Password: 
Linux raspberrypi 5.15.76+ #1597 Fri Nov 4 12:11:43 GMT 2022 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Aug 24 23:42:06 JST 2023 on ttyGS0

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~$  HISTCONTROL=ignoreboth
pi@raspberrypi:~$  sudo timedatectl set-timezone Asia/Tokyo
pi@raspberrypi:~$  sudo date 082423482023.25
2023年  8月 24日 木曜日 23:48:25 JST
pi@raspberrypi:~$  pwd
/home/pi
pi@raspberrypi:~$  cd -- $''
pi@raspberrypi:~$  ls -al --quoting-style=c
合計 40
drwxr-xr-x 5 pi   pi   4096  8月 24 23:33 "."
drwxr-xr-x 3 root root 4096 12月 12  2022 ".."
-rw------- 1 pi   pi    131  8月 24 23:33 ".bash_history"
-rw-r--r-- 1 pi   pi    220 12月 12  2022 ".bash_logout"
-rw-r--r-- 1 pi   pi   3523 12月 12  2022 ".bashrc"
drwxr-xr-x 3 pi   pi   4096 12月 12  2022 ".cache"
drwxr-xr-x 4 pi   pi   4096 12月 12  2022 ".npm"
-rw-r--r-- 1 pi   pi    807 12月 12  2022 ".profile"
drwxr-xr-x 3 pi   pi   4096  8月 24 23:32 "myApp"
-rw-r--r-- 1 pi   pi    142  8月 24 23:40 "wpa_supplicant.conf"
pi@raspberrypi:~$ pwd 
pi@raspberrypi:~$ /home/pi <== ※1 再起動後、ディレクトリ位置がルート
pi@raspberrypi:~/myApp$ ls -la
pi@raspberrypi:~$ cd myApp/ <== cd コマンド入力
pi@raspberrypi:~$ pwd 
pi@raspberrypi:~$ /home/pi/myApp <== ※2 初回起動時のディレクトリ位置
pi@raspberrypi:~/myApp$ ls -la
合計 80
drwxr-xr-x  3 pi pi  4096  8月 24 23:32 .
drwxr-xr-x  5 pi pi  4096  8月 24 23:33 ..
-rw-r--r--  1 pi pi 13947 12月 12  2022 RelayServer.js
-rw-r--r--  1 pi pi   777  8月 24 23:44 main-hello-real-world.js
drwxr-xr-x 28 pi pi  4096 12月 12  2022 node_modules
-rw-r--r--  1 pi pi 41564 12月 12  2022 package-lock.json
-rw-r--r--  1 pi pi  1845 12月 12  2022 package.json
pi@raspberrypi:~/myApp$ node main-hello-real-world.js <== 再度 Lチカプログラム実行無事起動
May be the first time port access. Retry..
^C
pi@raspberrypi:~/myApp$ ^C
```

**Comment by elie-j** [comment]
【参考】ご本人への連絡ログをこちらに転記します。

> satakagi
> コミュニティメンバーの一人が検証されましたが、再現しないようです。
> これまでも複数のかたがMacintoshで試されていましたが同様の不具合報告は受けておりませんので、
> 不具合が生じたかた、よろしければ現象の再現性の確認と、動作環境（Macintosの型番、OSのバージョン、Chromeのバージョン（M1ネイティブ版かどうか含む））を先のgithub issueもしくはこちらに投稿していただけると助かります。

--------

検証ありがとうございます。
認識しなくなるバグが生じた私のバージョンは以下のとおりです。
2020年モデルMacBook Air　FVFH40TBQ6LT
CPU: Apple M1
OS: macOS Ventura 13.4.1
chrome : バージョン: 115.0.5790.170（Official Build） （arm64）
表示のされ方的に設定する前まではusbメモリか何かとしてraspberry pi zeroが認識されているのだと思います。
デスクトップ上にUSBメモリを接続した時と同じようにアイコンが表示されました。

--------

**Comment by satakagi** [comment]
利用されたCHIRIMEN Liteイメージでは、USB OTGのマスストレージとシリアル通信の二つが同時に認識される設定になっています。([g_acm_ms](https://gist.github.com/gbaman/50b6cca61dd1c3f88f41))
従って、usbメモリのように認識されるのは正常に見えますので、Raspberry Pi Zero上でOSは起動し、USB OTGのドライバも正常に稼働していると思われます。

不具合が生じている状態が再現できれば、念のため、ioreg -p IOUSB　を使って、シリアル通信とマスストレージ(ACM + MS composite gadget などといった表示)コンポジットのデバイスが認識されていることを確認できていることを確認されると良いと思います。

また、マスストレージ機能に関しては以前不具合が見られた(ファイルを書き込むと起動しなくなった、など)とのことで、新しくリリースした[CHIRIMEN Liteイメージ 1.3.0](https://github.com/chirimen-oh/chirimen-lite/releases/tag/v1.3.0)ではマスストレージ機能を外し、シリアル通信機能のみに変更されています。
こちらの新しいイメージを使って試していただくと、動作が安定する可能性があります。（ユーザが意図しないタイミングでMacOSがマスストレージに書き込もうとする可能性を防げるため）

**Comment by gurezo** [comment]
## 検証マシン情報
### 2021 年11月モデル M1 Mac Book Pro

#### ハードウェア情報
- 10コアCPU、32コアGPU、16コアNeural Engine搭載Apple M1 Max
- 64GBユニファイドメモリ
- 1TB SSDストレージ
- 14インチLiquid Retina XDRディスプレイ
- Thunderbolt 4ポート x 3、HDMIポート、SDXCカードスロット、MagSafe 3ポート

#### ソフトウェア情報

- OS：macOS Ventura 13.5
- Google Chrome: 116.0.5845.110（Official Build） （arm64）
- CHIRIMEN OS Image: [2022-12-12-chirimen-lite](https://github.com/chirimen-oh/chirimen-lite/releases/tag/v1.2.0)

**Comment by elie-j** [comment]
microSDのバージョンアップ後、その後現象発生していません。
一旦クローズします。
