### ISSUE TITLE
[setup CHIRIMEN]を複数実行した際の振る舞いに関する提案

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/PiZeroWebSerialConsole#3]
バージョン: f746871 時点

[CHIRIMEN panel] > [setup CHIRIMEN] を選択し、実行完了後、再び [setup CHIRIMEN] を実行すると、すでに存在するいくつかファイルに関しては接尾辞 (".1" 等) が与えられ保存される振る舞いに見えます。
提案としては、すでにセットアップ後であればセットアップ不要であることを利用者に通知し実行を中断するか、(必要に応じてバックアップして)上書きするなどしておくほうが、よりべき等性が高まってユーザビリティの観点ではよいのではないかと考えます。

**Comment by satakagi** [comment]
上書きするようにしました。　更新する可能性があるため
