### ISSUE TITLE
起動時の自動実行手段に関する提案

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/PiZeroWebSerialConsole#5]
(ここではなく http://tutorial.chirimen.org/ へのフィードバックかもしれませんが、) USBシリアル接続を解除後、利用者が開発したアプリケーションの自動実行可能にするためのガイドがあるとよりよいと考えました。

**Comment by satakagi** [comment]
CHIRIMENパネルに、foreverを使った設定UIをつくってみました。
https://github.com/chirimen-oh/PiZeroWebSerialConsole/commit/475281eee63c75628f7174103689d9001a1909d6

**Comment by kou029w** [comment]
@satakagi ありがとうございます! 自動実行するための仕組みが利用者に提供されていて良さそうに見えます :+1: よって本件クローズしますね。
